name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REPO_NAME: ghcr.io/Bevynator/cdk8s-on-argocd

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./typescript/
          push: true
          tags: ${{ env.REPO_NAME }}:${{ github.sha }}, ${{ env.REPO_NAME }}:latest

      - name: Log out of GitHub Container Registry
        run: docker logout ghcr.io
